# jail.conf for container: nginx
# Included by the default recipes/jail.conf.
# Shared defaults (exec.start, mount.devfs, etc.) are inherited.
# See jail.conf(5) for options.

nginx {
    host.hostname = "nginx";
    path = "/containers/nginx";
    mount.fstab = "/zshemot/recipes.git/containers/nginx/mount.fstab";
}
