# jail.conf for container: recipya
# Included by the default recipes/jail.conf.
# Shared defaults (exec.start, mount.devfs, etc.) are inherited.
# See jail.conf(5) for options.

recipya {
    host.hostname = "recipya";
    path = "/containers/recipya";
    mount.fstab = "/zshemot/recipes.git/containers/recipya/mount.fstab";
}
